Restore dev-stephyr amzn buildspec to check if it builds

diff --git a/buildspecs/pr-build-amzn.yml b/buildspecs/pr-build-amzn.yml
--- a/buildspecs/pr-build-amzn.yml
+++ b/buildspecs/pr-build-amzn.yml
@@ -46,19 +46,40 @@ phases:
       - AL23_VERSION="$(curl -s https://al2023-repos-us-west-2-de612dc2.s3.dualstack.us-west-2.amazonaws.com/core/releasemd.xml | xmllint --xpath "string(//root/releases/release[last()]/@version)" -)"
       - AGENT_VERSION="$(cat VERSION)"
 
-      - |
-        if [[ "$amzn_version" = "amzn2023" ]]; then
-          echo "Amazon Linux 2023 Version: $AL23_VERSION" 2>&1 | tee -a $BUILD_LOG
-        fi
-
       # Need to install GOLANG explicitly as required versions do not come preinstalled
       # Remove existing go installation (goenv utility)
       - sudo rm -rf /root/.goenv
-      - export GOROOT=/usr/local/go
-      - export PATH=/usr/local/go/bin:$PATH
+      - sudo rm -rf /usr/local/go/bin/go 
 
-       # Install the specified Go version using the install-golang make target
-      - make install-golang
+      # Define the Go version to install
+      - GOVERSION="$(cat GO_VERSION)"
+
+      # Install Go and define variables based on Amazon Linux version (2 or 2023)
+      # Amazon Linux 2023 uses package manager DNF, while older versions use YUM
+      # First, try to install the specified Go version, if unable, install latest Go version available
+      - |
+        if [[ "$amzn_version" = "amzn2023" ]]; then
+          sudo dnf --releasever="$AL23_VERSION" update -y
+          echo "Amazon Linux 2023 Version: $AL23_VERSION" 2>&1 | tee -a $BUILD_LOG
+          if sudo dnf install -y golang-$GOVERSION; then
+            echo "Installed Go version: $GOVERSION" 2>&1 | tee -a $BUILD_LOG
+          else
+            echo "Specified Go version $GOVERSION not found, installing latest available version" 2>&1 | tee -a $BUILD_LOG
+            sudo dnf install -y golang
+          fi
+
+        elif [[ "$amzn_version" = "amzn2" ]]; then
+          if sudo yum install -y golang-$GOVERSION; then
+            echo "Installed Go version $GOVERSION" 2>&1 | tee -a $BUILD_LOG
+          else
+            echo "Specified Go version $GOVERSION not found, installing latest available version" 2>&1 | tee -a $BUILD_LOG
+            sudo yum install -y golang
+          fi
+
+        else
+          echo "Unsupported Amazon Linux version"
+          exit 1
+        fi
 
       # Define the log file with AL version (amzn2 or amzn23) and the architecture
       - BUILD_LOG="build_${amzn_version}_${architecture}.log"
@@ -84,7 +105,6 @@ phases:
         if [[ $GITHUBUSERNAME != "aws" ]]; then
           mv $GITHUBUSERNAME aws
         fi
-      - echo $(pwd) 2>&1 | tee -a $BUILD_LOG
       - cd aws/amazon-ecs-agent
 
       # Build Amazon Linux RPM
